### ISSUE TITLE
Do not remember passwords in browser for STF page

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/stf#114]
**What is the issue or idea you have?**
Currently almost impossible to manually work with STF from Chrome if you already submit any login\password details

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
All devices

**Please provide the steps to reproduce the issue.**
1. Have any application on device with login fields (for example google account).
2. Submit correct credentials in chrome
3. Refresh page
4. Try to do anything manually on any device with mouse clicking.
**What is the expected behavior?**
Everything should be ok
**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
Popup with all stored credentials is shown each mouse click

**Comment by Alexandr611** [comment]
closed by PR - https://github.com/qaprosoft/stf/pull/122
