### ISSUE TITLE
Add ability to unlock device screen from iSTF

### ISSUE THREAD

**Issue by kolyakrasnik** [qaprosoft/stf#123]
Currently we are not able to unlock screen from iSTF.

**Comment by kolyakrasnik** [comment]
As a decision click to home button via WDA https://github.com/appium/appium-xcuitest-driver/blob/master/docs/endpoints-wda.md

**Comment by Alexandr611** [comment]
Already have been implemented unlock/lock feature - https://github.com/qaprosoft/stf/pull/49
