### ISSUE TITLE
Screenshot's not working

### ISSUE THREAD

**Issue by dhreben** [qaprosoft/stf#136]
1. Open http://stf-stage.solvd.com/#!/devices
2. Enter your login and password
3. Open any device
4. Tap screenshot
Actual result: Screenshot's not working.
Expected result: Screenshot works.

**Comment by vdelendik** [comment]
it should be already fixed in 3.1 for all production environments.
in scope of 3.2 improvement delivered: https://github.com/qaprosoft/stf/pull/152
it should simplify configuration steps making it workable by default

**Comment by dhreben** [comment]
fixed
