### ISSUE TITLE
OS column iPhone 7 and Ipad air2  does not show the version of device

### ISSUE THREAD

**Issue by dhreben** [qaprosoft/stf#138]
Steps:
1. Open http://stf-stage.solvd.com/#!/devices
2. Enter your login and password
3. Tap details
       Actual result: OS column iPhone 7 and Ipad air2 does not show the version of the device
<img width="1389" alt="Screen Shot 2020-03-23 at 20 48 05" src="https://user-images.githubusercontent.com/50950954/77348134-fe04f780-6d49-11ea-92be-80777f49c8b8.png">

**Comment by vdelendik** [comment]
need to re-test again using 3.1 stf version

**Comment by dhreben** [comment]
fixed
