### ISSUE TITLE
Error at startup STF

### ISSUE THREAD

**Issue by dhreben** [qaprosoft/stf#141]
Steps:
1. Open http://stf-stage.solvd.com
2. Enter your login and password

Actual result: Error at startup STF

<img width="771" alt="Screen Shot 2020-03-26 at 13 46 47" src="https://user-images.githubusercontent.com/50950954/77645689-30923880-6f74-11ea-8e2f-f705e1b7c704.png">

**Comment by vdelendik** [comment]
conflicts between stf and zafira resolved. in 5.1 qps-infra SmartTestFarm moved under independent "/stf" context root path.
to test use http://stage.solvd.com/stf url - already configured using 3.2-beta2 stf build

**Comment by dhreben** [comment]
fixed
