### ISSUE TITLE
Gray screen on the device

### ISSUE THREAD

**Issue by dhreben** [qaprosoft/stf#142]
Steps:

1. Open http://stf-stage.solvd.com
2. Enter your login and password
3. Open any device

Actual result: Gray screen on the device
<img width="936" alt="Screen Shot 2020-03-26 at 13 47 01" src="https://user-images.githubusercontent.com/50950954/77646404-85827e80-6f75-11ea-802e-b8f7a02f7e0e.png">

**Comment by vdelendik** [comment]
fixed on http://stage.solvd.com/stf (3.2-beta2)
pay attention that url has the same fqdn name as qps-infra (no need to register extra DNS for that part of services)

**Comment by dhreben** [comment]
fixed
<img width="623" alt="Screen Shot 2020-07-14 at 15 08 08" src="https://user-images.githubusercontent.com/50950954/87423957-d630ec80-c5e3-11ea-9313-b4379927c3e0.png">
