### ISSUE TITLE
/data folder should be writable for default stf user

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/stf#149]
Unable to make a screenshot until share folder with rwx permissions for everyone.
We have to investigate howto create "/data " preliminary and make stf user as owner.
that should allow to share it via docker volume

**Comment by ilya-varchenya** [comment]
![image](https://user-images.githubusercontent.com/44428408/85848891-a5af1d00-b7b2-11ea-8fb8-805cd049669f.png)

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/stf/pull/152

**Comment by vdelendik** [comment]
agreed with @ilya-varchenya to test on our own
