### ISSUE TITLE
unable to make a screenshot without extra permissions setup

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/stf#155]
inside stf-storage-temp container "/data" shared location belongs to root. As result we have to share and provide extra call via chmod operation otherwise not enough permissions detected.

we have to create explicitly "/data" folder and change ownership to "stf" user

**Comment by vdelendik** [comment]
/data folder generated as part of Dcokerfile instructions and valid permissions assigned: https://github.com/qaprosoft/stf/pull/156/files#diff-3254677a7917c6c01f55212f86c57fbfL43

as a test scenario - reuse qps-infra release candidate build (coming soon as 5.1-rc1) and integrate android or iOS device for that.

**Comment by dhreben** [comment]
fixed
<img width="982" alt="Screen Shot 2020-07-14 at 19 01 30" src="https://user-images.githubusercontent.com/50950954/87466811-9e479a80-c61f-11ea-9f91-1c63328431a4.png">
