### ISSUE TITLE
iOS: dashboard tab

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/stf#18]
sorted by priority from highest:
-Logs
-Navigation
-Clipboard
-Shell (???)

**Comment by Alexandr611** [comment]
WebDriverAgent don't support logs.So it's recommended to investigate Appium capabilities.

**Comment by Alexandr611** [comment]
-Logs
-Navigation
the following features were made

**Comment by Alexandr611** [comment]
-Shell doesn't support for IOS devices(
There is some libs as simctl but this lib support only simulators.

**Comment by vmartsunyk** [comment]
In the Dashboard Apps was added:
- App Store
- Settings
