### ISSUE TITLE
Scroll doesn't work after rotate screen into landscape mode

### ISSUE THREAD

**Issue by Dzias7** [qaprosoft/stf#25]
Summary:
Scroll doesn't work after rotate screen into landscape mode

Steps to reproduce:

1.open safari browser
2.type wikipedia.org (or any other website address) into the address bar
3.tap on landscape icon

Actual result:
Scroll doesn't work after rotate screen into landscape mode

Expected result:
Ability to scroll the page

**Comment by Alexandr611** [comment]
https://github.com/qaprosoft/stf/commit/2a868e8fa96a43cff43ef0d7a2b847e70b778c31
@Dzias7
bug with rotation event was fixed
