### ISSUE TITLE
Stf UI freezes after closing applications from the device memory

### ISSUE THREAD

**Issue by Dzias7** [qaprosoft/stf#26]
Preconditions:
open several applications (at least 5) in the background mode

Steps to reproduce:

1.double tap on home button
2.swipe up and close all background applications

Actual result:
Stf UI freezes after closing applications from the device memory
Expected result:
Stf UI continue to display the content

**Comment by Alexandr611** [comment]
I could not reproduce this error.
This bug may have occurred due to system limitations.
