### ISSUE TITLE
Press and swipe functions are inactive after typing url into the navigation field

### ISSUE THREAD

**Issue by Dzias7** [qaprosoft/stf#27]
Steps to reproduce:

1.Type wikipedia.org (or any other website address) into the navigation field and click Open 
2.Click home button and wait about 20-30 sec until you get to the main screen
3.From the main screen tap on any icon / swipe any directions

Actual result:
Press and swipe functions are inactive, istf UI become inactive

Expected result:
User is able to proceed interaction with iSTF ui

**Comment by Alexandr611** [comment]
The bug is created by the limitations of the system.
The issue is closed due to the limitations of the system and the inability to solve the bug.
