### ISSUE TITLE
Placeholder is displayed instead of screenshot

### ISSUE THREAD

**Issue by Dzias7** [qaprosoft/stf#28]
Steps to reproduce:

1.Go to "Screenshots" tab
2.Tap on "Screenshots" button

Actual result:
Placeholder is displayed instead of screenshot

Expected result:
Correspondent screenshot is displayed

Attachment:

![screenshot_2](https://user-images.githubusercontent.com/28729017/51185432-2bede100-18e8-11e9-9a0a-cd857fc1e457.png)

**Comment by Alexandr611** [comment]
https://github.com/qaprosoft/stf/commit/2a868e8fa96a43cff43ef0d7a2b847e70b778c31
bug with sceencapture was fixed
