### ISSUE TITLE
Landscape mode doesn't work within settings and default apps

### ISSUE THREAD

**Issue by Dzias7** [qaprosoft/stf#29]
Preconditions:
Test has been also performed on a several default apps such as: clock ,calendar,app store,itunes store. The result is the same - landscape mode doesn't work.

Steps to reproduce:

1.Tap on settings icon
2.Tap on landscape icon

Actual result:
Landscape mode doesn't work

Expected result:
Landscape mode works

Attachments:

![screenshot_1](https://user-images.githubusercontent.com/28729017/51194011-3ebde100-18fb-11e9-86fe-4001ad938a22.png)

![screenshot_2](https://user-images.githubusercontent.com/28729017/51194027-43829500-18fb-11e9-9336-e48ccd49ca81.png)

![screenshot_3](https://user-images.githubusercontent.com/28729017/51194037-48dfdf80-18fb-11e9-9a9c-b4a4a32aade2.png)

**Comment by Alexandr611** [comment]
There is no Landscape mode in "clock ,calendar,app store,itunes store".
