### ISSUE TITLE
Memory chart, memory usage

### ISSUE THREAD

**Issue by Alexandr611** [qaprosoft/stf#31]
![image](https://user-images.githubusercontent.com/24940437/51473387-e8322600-1d84-11e9-92d3-4a057f26c556.png)

Implement chart which allow to show in real time memory usage of application which are testing.

**Comment by vdelendik** [comment]
@Alexandr611 really in real time? or just periodically..

**Comment by Alexandr611** [comment]
@vdelendik i guess we can use socket connections to bring real time chart or use http to periodically rerender chart.
