### ISSUE TITLE
Add CLI options to ios-device iproxy usage

### ISSUE THREAD

**Issue by Alexandr611** [qaprosoft/stf#51]
### Add CLI options to ios-device iproxy usage
If the option with iproxy is passed, use proxy connection with devices.
example of CLI command :
`stf local --iproxy=true`
`stf ios-device --iproxy=true`
`stf ios-provider --iproxy=true`

**Comment by Alexandr611** [comment]
Also, add CLI option for devices IP address file(.json format)
`stf local --iputil=<path_to_file>`

**Comment by Alexandr611** [comment]
If the device doesn't mention in the local or remote file all devices are freezing. For fixing this bug should be added validations before starting device in ios-provider/ios-usb if the device is configured and only then start it.
- Delete iputil.js and replace it with ios-device.json as default file with device's ip-addresses in root folder of stf.
- Add validation on existences remote udid-storage file. 
- In additional rebuild format of a given file with more information.
- Provided additional documentation in README.MD for successful connection iSTF with configured devices.

**Comment by vmartsunyk** [comment]
- Verification is added before connecting the device
- File with devices is located to root directory
- Added validation on existences remote udid-storage file.
- Provided additional documentation in README.MD 
- Added possibility select connection(iproxy)
