### ISSUE TITLE
Unhandled rejection, in some cases istf-device lost connection with WDA stream

### ISSUE THREAD

**Issue by Alexandr611** [qaprosoft/stf#59]
### Unhandled rejection, in some cases istf-device lost connection with WDA stream
![image](https://user-images.githubusercontent.com/24940437/55223168-48769580-5216-11e9-9bfb-c3ee9bbb624d.png)
To reproduce this bug need to launch need to use more than one device.
You can see logs in system console/terminal where istf are running.

**Comment by vdelendik** [comment]
seems like fixed indirectly. @Alexandr611, please test and close as well
