### ISSUE TITLE
By passing time istf network traffic becomes slower and slower. So images don't send with normal speed.

### ISSUE THREAD

**Issue by Alexandr611** [qaprosoft/stf#60]
### By passing time istf network traffic becomes slower and slower. So images don't send with normal speed.
Check if weak network traffic related with a weak performance on the host machine.

**Comment by vdelendik** [comment]
that's a problem with STF ios-device service. As only I restart STF ios-device service the same old WDA works like a sharm

**Comment by Alexandr611** [comment]
closed by - https://github.com/qaprosoft/stf/pull/120
