### ISSUE TITLE
Add ability to connect to iSTF device for remote debugging.

### ISSUE THREAD

**Issue by kolyakrasnik** [qaprosoft/stf#89]
Let's add to ```remote debug``` area info about appium, related to the device. So, we'll be able to connect to the device remotely for debugging.

**Comment by Alexandr611** [comment]
1. rename stf_min_port to stf_screen_port (getDeviceArgs.sh) & CLI
2. remove completely stf_max_port getDeviceArgs.sh and devices.txt 
3. add stf_appium_port instead of stf_max_port & CLI

**Comment by Alexandr611** [comment]
closed by PR - https://github.com/qaprosoft/stf/pull/121
